### ISSUE TITLE
Pointing to live version of brutal.js

### ISSUE THREAD

**Issue by newyork-anthonyng** [crislin2046/rvanillatodo#5]
We have `brutal.js` hardcoded in this project. I think we should point to a live version, such as `https://unpkg.com/brutalist-web`. Let me know if this is a good idea.

## On a side note
Pointing to the new `1.2.0` version is breaking the TodoMVC example.
![screen shot 2018-07-20 at 10 14 54 am](https://user-images.githubusercontent.com/14035529/43007328-0685bf1a-8c06-11e8-99ef-da1c20bb6017.png)

**Comment by crisdosaygo** [comment]
I think this is a good idea, @newyork-anthonyng 😄
